# Generated by Django 5.1 on 2024-08-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone', models.IntegerField(max_length=11)),
                ('birth', models.DateField()),
                ('member_rccg', models.TextField()),
                ('whatsapp_no', models.IntegerField()),
                ('referee', models.TextField()),
                ('attended_prev', models.TextField()),
                ('suggestions', models.TextField()),
            ],
        ),
    ]
