# Generated by Django 5.1 on 2024-08-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_people_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='attended_prev',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='people',
            name='member_rccg',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='people',
            name='whatsapp_no',
            field=models.CharField(max_length=20),
        ),
    ]
